### ISSUE TITLE
Implement stricter clang-format sanity

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-common#10]
- We should enforce a (minimum) version. Using 3.5 now fubars code tree for example
- clang-format's apparently ok with not finding a spec file and falls back on LLVM, which also fubars our entire tree. Maybe the collection/high-level "format" target could check ```.clang-format``` presence?

**Comment by ftalbrecht** [comment]
* Agreed. Minimum is 3.7, as we use some options which are not there in older versions.
* Yes, and check the version of clang.

In addition: we/I need to implement a corresponding travis/something else configuration which checks for correct formatting...

**Comment by renemilk** [comment]
I did already start with the addition a while back :smile: :
https://github.com/dune-community/dune-xt-common/blob/master/.travis.yml#L75
https://github.com/wwu-numerik/scripts/blob/master/python/travis_report.py
https://travis-ci.org/dune-community/dune-xt-common/jobs/104854872#L3553

Which is currently failing for either wrong token or undiscovered reasons.

**Comment by ftalbrecht** [comment]
K, nice! So I guess we should check for the correct clang version and presence of `.clang-format` also in the `pre-commit.clang-format` script...

**Comment by ftalbrecht** [comment]
Very nice, thx!
