### ISSUE TITLE
Provide access to config.h constants to python bindings

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-common#120]
I see a couple of options:
  - use libclang to parse config.h and just expose everything. Downside: clang is now needed even if you compile with gcc. Upside: We can to lots other cool stuff with libclang now too. See also 
  - hardcode a few "interesting" constants only
  - use something other than liblang and that is contained in one shippable script to parse config.h. Downside: I do not want to write that script. 

As for how the extracted constants are exposed, that's also somewhat tricky since the config.h headers definitions of the same constants may var between dune-modules. I'm currently thinking of a global data structure under dune.xt.config that each module then updates. Maybe warn if it overwrites a constant with a different value. The other option would be a config object per dune-module, but that's not practical in usage and does not deal with inconsistencies at all.

Thoughts, @dune-community/dune-xt-contributors , @dune-community/dune-xt-devs ?

**Comment by tobiasleibner** [comment]
I like option 1. Maybe we can disable the python bindings if clang is not available, or just provide a default config where everything is set to false/some default value  (and give a warning that default values are used as clang is not available)?
As for the exposure of the constant, shouldn't we do the same as is done on the C++ side? So if every module uses its own config.h, wouldn't it be inconsistent to use a global config.h in python? It might be confusing if the behavior depends on whether you call something through the python-bindings or directly in C++.

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
