### ISSUE TITLE
Switch to 2.6 Core modules?

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-common#143]
As we are changing to the new-master branches currently and are not backwards compatible anyway, we could also switch from ``releases/2.5`` to ``releases/2.6``. I created branches ``compatible_with_2.6`` in all xt modules, dune-xt-super and dune-pybindxi. Locally, all tests are passing for me. 

The main changes we have to do are related to the python changes (the functionality from the old dune-python moved to dune-common). Other than that, there are only minor changes. 

It probably would be possible to support both 2.5 and 2.6, but it might be annoying to get the cmake python stuff right. So I would suggest dropping support for 2.5 and requiring 2.6. Any opinions?

**Comment by ftalbrecht** [comment]
Done by now
