### ISSUE TITLE
Add common statistics functions for vector interface types

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-common#2]

**Comment by renemilk** [comment]
Basically we'd a free function to calc the std.dev. of vector-likes. Boost accumulators may be a good choice. 
Ref: https://github.com/dune-community/dune-xt-common/blob/master/dune/xt/common/localization-study.cc#L121

**Comment by renemilk** [comment]
Added std.dev., everybody feel free to add as needed or reopen.
