### ISSUE TITLE
Add tests for currently untested code

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-common#20]
**Moved from https://github.com/wwu-numerik/dune-stuff/issues/69**

Non-exhaustive list of code that should have at least rudimentary test coverage. As in does it compile in the usual use-case. 
## Common
- [ ] ConvergenceStudy, LocalizationStudy (probably used in another module's tests?)
- [ ] filesystem.hh: esp. error conditions for stream creation
- [ ] misc.hh (wraparound_array)
- [ ] random.hh

**Comment by renemilk** [comment]
- [ ] DUNE_THROW_IF

**Comment by renemilk** [comment]
See also https://codecov.io/gh/dune-community/dune-xt-common/tree/master/dune/xt/common

**Comment by ftalbrecht** [comment]
Wow, this looks like an actually useful report!

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
