### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-common#204]
Each xt module has about 20 branches. Many of these branches seem to be leftovers from previous PRs that have not been deleted after merging. Before archiving the modules we should delete all branches that are not needed anymore. Otherwise, it might be hard in the future to distinguish which branches actually contain useful code.

**Comment by tobiasleibner** [comment]
From my side, only the ``releases/*`` branches here are important.

**Comment by tobiasleibner** [comment]
Before archiving, we should:
- Delete unused branches, for me everything expect the ``releases/*`` branches can be removed. Other opinions, @dune-community/dune-xt-devs?
- Update Readme to point to the new dune-xt repository

**Comment by ftalbrecht** [comment]
We should check which branches are referenced/used referenced in publications, and keep those. Probably best if each of us lists the ones he still requires.

**Comment by tobiasleibner** [comment]
We decided not to delete the branches before archiving. Readme is updated, so we are finished here.
