### ISSUE TITLE
[cmake] fix broken testing

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-common#25]
Something is wrong, see for instance https://travis-ci.org/dune-community/dune-xt-common/jobs/170406859. I think it is related to 52b4275b9477b3feddeefc00bd2155d63b9e809d, since I do not get those errors in a pr which does not contain this commit.

**Comment by renemilk** [comment]
Before the gitlab cloning failed again this was fixed, no?

**Comment by renemilk** [comment]
@dune-community/dune-xt-common-devs is this still an issue? At least master seems fine now, no?

**Comment by ftalbrecht** [comment]
Master fails currently, prolly not realted. Can be closed IMHO.
