### ISSUE TITLE
Make use of the ```dune-ctest``` wrapper

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-common#26]
[Reference](https://gitlab.dune-project.org/core/dune-common/commit/d0ab191fda4ff95613c37d53a330c69766b13ce1)
 
While I haven't run into an issue with ctest unexpectedly returning non-zero, this might be something to consider in the future.

**Comment by renemilk** [comment]
This should also remove the need to have https://github.com/dune-mirrors/dune-testtools/commit/b61c7be7f647b7123581031c663488d2a347cb8c reverted in our testtools modules, but needs adjusting of all travis scripts.

**Comment by tobiasleibner** [comment]
Is this still something we would like to have?

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
