### ISSUE TITLE
hard dependency on numa

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-common#29]
Since ff1b19df72c21bc9a5aef583d6667ff0c449f293 we have a hard dependency on numa. If the headers are not present, dunecontrol will fail. We maybe want to do something about that (or about python deps which require development headers to be installed in general)...

**Comment by renemilk** [comment]
Sorry, that behaviour's new. Before (2.5 ?) dunecontrol allowed (silently) failures in setting up dependencies.
