### ISSUE TITLE
improve fieldvectors/matrices

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-common#36]
In the long run we want to use our FieldVector and FieldMatrix everywhere (in particular in dune-gdt), as providing operators for the ones from dune-common becomes increasingly difficult to maintain. So we need to do the following:

* all operators in fvector/fmatrix which return something should return promoted types
* all operators in fvector/fmatrix have to return _our_ fvector/fmatrix, we thus need to overwrite all operators from base
* we have to return our variants of fvector/fmatrix _everywhere_ in dune-xt and dune-gdt where something new is created (in particular in the functions in dune-xt-functions)

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
