### ISSUE TITLE
from_string<std::complex<...>>() broken for certain strings

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-common#39]
Our convention is to interprete strings of the kind `"a+bi"` and `"a-bi"` as complex numbers, if `a` and `b` are string representations of real numbers. This does not work if `a` is given in scientifi notation, i.e. `1e-10`.

**Comment by ftalbrecht** [comment]
Probably the easiest fix would be to change our interpretation of complex to `"(a,b)"`. This is easier to parse, does not interfer with the rest of the string parsing (we only use "[" and ';') and is the format we have when printing `std::complex` via `std::cout` (So one can easily copy printed complex numbers).

**Comment by renemilk** [comment]
I'd be happy with the tuple notation

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
