### ISSUE TITLE
[CONTRIBUTING] update

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-common#4]

**Comment by renemilk** [comment]
Still want to change something?
https://github.com/dune-community/dune-xt-common/edit/master/CONTRIBUTING.md

**Comment by ftalbrecht** [comment]
One link to the official dune sites is dead by now, we would need a replacement. Apar tfrom that, we could give mor information about the clang-format hook being deplyed with dune-control?

**Comment by renemilk** [comment]
Not sure what more to add wrt the format hook, @ftalbrecht

**Comment by ftalbrecht** [comment]
Nothing, you are right. But we should check the links...

**Comment by renemilk** [comment]
The only dead one seems to be http://users.dune-project.org/projects/main-wiki/wiki/Guides_bug_reporting
I have no idea what that said, do you?

**Comment by ftalbrecht** [comment]
It gave general advice on how to report bugs and which informatin to provide. Allegedly, they are moving the old homepages but I could not find that information anywhere...
