### ISSUE TITLE
Enable branch protection for master? 

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-common#55]
I think we all agreed to do this already. The question now is how strict a setup we want?https://help.github.com/articles/defining-the-mergeability-of-pull-requests

**Comment by ftalbrecht** [comment]
Without too much thought I would think that

* test have to pass
* up-to-date with base is not required (as long as there are no merge conflicts), since travis also tests push
* review is not required (this would not make sense for small `dailywork`-like branches

**Comment by renemilk** [comment]
While I agree on the tests having to pass bit, there's a corner case to consider: https://github.com/dune-community/dune-xt-la/pull/33#issuecomment-366801196
I'm not sure if we can solve this nicely.

Other two points: agreed.

**Comment by ftalbrecht** [comment]
True. In that case (if getting tests to pass is too difficult) I would
think that one other review would at least be _nice_, though not
necessarily mandatory.

**Comment by renemilk** [comment]
I've enabled protection for master for dune-xt-{la,grid,common,functions} and dune-gdt  now.
Requiring travis builds is not tunable to include only Push builds. So currently the protection counts for both PR and Push. I guess we'll see how that works for us.
