### ISSUE TITLE
Reduce number of xt-dev teams to one? 

### ISSUE THREAD

**Issue by renemilk** [dune-community/dune-xt-common#56]
I don't think I've ever had a use case for the fine grsined setup we have now.

**Comment by ftalbrecht** [comment]
As in `dune-xt-foo-devs` -> `dune-xt-devs` for `foo` in `common`, `la`, `grid`, `functions`? Agreed.

**Comment by renemilk** [comment]
Yeah, exactly.

**Comment by renemilk** [comment]
I've setup @dune-community/dune-xt-devs to have write access to dune-xt-super, dune-xt-{la,grid,common,functions}[-testlogs]
