### ISSUE TITLE
[common.color] allow to disable globally

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-common#6]
_From @ftalbrecht on October 26, 2015 17:12_

We should add `DUNE_STUFF_DISABLE_COLORS`. If defined, this should disable colored output (e.g., by returning empty strings as colors).

_Copied from original issue: wwu-numerik/dune-stuff#85_

**Comment by renemilk** [comment]
This should now be ```DXT_DISABLE_COLORS```

**Comment by ftalbrecht** [comment]
Feel free to reopen if someone is interested
