### ISSUE TITLE
take directory structure into account in test target name generation

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-common#64]
Currently, given the filesystem structure
```
dune/foo/test/bar/buzz.cc
```
our cmake stuff creates the test target `test_buzz`, which usually results in
```
dune/foo/test/bar/bar_buzz.cc
```
for thematically grouped tests, to obtain a `test_bar_buzz` target. It would be nice if the cmake stuff took the directory structure into account in the generation of the target name, i.e.
```
dune/foo/test/bar/buzz.cc
```
becomes `test__bar__buzz`. Yes, I am friend of double `_`, think of:
```
dune/gdt/test/localizable-operators/weighted-l2-product.cc
```
I would rather have the test target be named
```
test__localizable_operators__weighted_l2_product
```
as opposed to
```
test_localizable_operators_weighted_l2_product
```
since the latter looses the structural information.

**Comment by tobiasleibner** [comment]
Moved to dune-xt.
