### ISSUE TITLE
[common.color] make use of background coloring

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-common#7]
_From @ftalbrecht on September 24, 2015 16:21_

We color strings for output in several places, usually without setting a background color. This may lead to hard to read terminal output, depending on the color scheme of the terminal.

We should thus consider to color the background, e.g., in the `TimedLogger`...

_Copied from original issue: wwu-numerik/dune-stuff#75_

**Comment by renemilk** [comment]
There's no way of _getting_ the background color programmatically though, right?

**Comment by renemilk** [comment]
_From @ftalbrecht on September 25, 2015 7:3_

Not that I know of, no.

I am not sure if there is a generic way of handling this problem at
all. But since I will have to adapt the `TimedLogger` at some point
(boost timer, for instance), I wanted to have a reminder to reconsider
the matter...

**Comment by renemilk** [comment]
Pretty sure the answer is "not really" or is at least depending on how broad your definition of "generic" is. See also https://stackoverflow.com/questions/2507337/is-there-a-way-to-determine-a-terminals-background-color

**Comment by renemilk** [comment]
Another solution to this problem might be configurable colors. Not that I want that or would consider implementing it, just saying it would prolly be a cleaner solution.

**Comment by renemilk** [comment]
Something to look at: https://raw.githubusercontent.com/agauniyal/rang/master/include/rang.hpp

**Comment by ftalbrecht** [comment]
Please reopen if someone is interested
