### ISSUE TITLE
[common.logging] improve

### ISSUE THREAD

**Issue by renefritze** [dune-community/dune-xt-common#8]
_From @ftalbrecht on September 24, 2014 12:21_
- use boost::date_time internally to get wall time
- add support for threaded environments (levels need to be per thread)
- add thread/process number to ouput (if more than one), ala `00:00|thread_number|prefix: foo` 

_Copied from original issue: wwu-numerik/dune-stuff#16_

**Comment by renemilk** [comment]
The TimedLogger should also be removed and integrated as a stream type/setup option into the main one. Adding new streams via integer id is also too cumbersome. This should be per string id.

**Comment by tobiasleibner** [comment]
Closing this, feel free to reopen in ``dune-xt``.
